name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        aggregates: [0, 1]
        include:
          - toolset: gcc
            compiler: g++-6
            version: "6"
            cppstd: "11 14 17"
            install: g++-6
          - toolset: gcc
            compiler: g++-8
            version: "8"
            cppstd: "11 14 17 20"
            install: g++-8
          - toolset: gcc
            compiler: g++-9
            version: "9"
            cppstd: "11 14 17 20"
            install: g++-9
          - toolset: gcc
            compiler: g++-10
            version: "10"
            cppstd: "11 14 17 20"
            install: g++-10
          - toolset: clang
            compiler: clang++-3.9
            version: "3.9"
            cppstd: "11 14"
            install: clang-3.9
          - toolset: clang
            compiler: clang++-5.0
            version: "5.0"
            cppstd: "11 14 17"
            install: clang-5.0
          - toolset: clang
            compiler: clang++-10
            version: "10"
            cppstd: "11 14 17 20"
            install: clang-10

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Install Packages
          run: |
            echo "deb http://archive.ubuntu.com/ubuntu bionic main universe" | sudo tee -a /etc/apt/sources.list
            sudo apt update
            sudo apt install ninja-build ${{matrix.install}}
            pip install conan

        - name: Build
          run: |
            for cppstd in ${{matrix.cppstd}}
            do
              if [[ "${{matrix.aggregates}}" -eq "1" ]] && [[ "$cppstd" -le "14" ]]; then
                continue
              fi

              conan install . -if=build -b=missing \
                -s compiler=${{matrix.toolset}} \
                -s compiler.version=${{matrix.version}} \
                -s compiler.cppstd=${cppstd} \
                -s compiler.libcxx=libstdc++11 \
                -e CXX=${{matrix.compiler}}
              cmake -Bbuild -H$GITHUB_WORKSPACE \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
                -DCMAKE_CXX_STANDARD=${cppstd} \
                -DCMAKE_CXX_STANDARD_REQUIRED=ON \
                -DCMAKE_CXX_EXTENSIONS=OFF \
                -DHIPONY_ENUMERATE_AGGREGATES_ENABLED=${{matrix.aggregates}} \
                -G Ninja
              cmake --build build
            done
